apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q3ojcwp8w-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/q3ojcwp8w-java-quarkus-gitops